### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adniec** [ethru/pdoc3-mdnotes#1]
@kernc I would like to create extension to pdoc. My code do not modify pdoc installation itself. I used tips from [docs](https://pdoc3.github.io/pdoc/doc/pdoc/#programmatic-usage) to import and adjust pdoc to extension needs. I have also modified original templates. My question is am I allowed to use MIT license in this case? Should I include any additional information? I was planning to add something like this:

>#### License:
>This project is under the MIT License - see the LICENSE file for details. It bases on *pdoc* functionality please visit [website](https://pdoc3.github.io/pdoc/) to get more information and see pdoc [license](https://raw.githubusercontent.com/pdoc3/pdoc/master/LICENSE.txt).
>
>***Note:*** *this extension does not modify [pdoc](https://pdoc3.github.io/pdoc/) installation. It is separate module which uses elements provided by [pdoc](https://pdoc3.github.io/pdoc/doc/pdoc/#programmatic-usage) to generate html notebook from markdown files. For this purpose original templates were downloaded and adjusted from [source](https://github.com/pdoc3/pdoc/tree/master/pdoc/templates).*

If I can not use MIT license or need to enclose some other information would you please correct me and tell how it should be done.

**Comment by kernc** [comment]
Yeah, the same "issue" was discovered by @timothycrosley while working on [portray](https://github.com/timothycrosley/portray). He quickly decided AGPL was too dirty in all respects and forked original pdoc Unlicensed code as [pdocs](https://github.com/timothycrosley/pdocs/) ...

I was thinking about it since, but haven't yet reached a decisive conclusion. Was most leaning towards something like ["Lesser AGPL"](http://mo.morsi.org/blog/2009/08/13/lesser_affero_gplv3/), i.e. AGPL with linking exclusion. That's not a [widely-recognized license](https://spdx.org/licenses/), though, and, more importantly, probably results in being able to circumvent AGPL's network-use-is-distribution limitation by wrapping pdoc3 call in a simple e.g. MIT-licensed shell script, resulting in the generated output being recognized wholly as that of the latter software.

Even with LAGPL, it also wouldn't really apply in your case of templates, since the templates are part of the distribution and, as of yet, no exclusion is set upon them either. You'd need to write your own. :rofl:

Now, any connection to AGPL whatsoever, even by extension, should certainly taint your project and make it unavailable in [many environments](https://opensource.google/docs/using/agpl-policy/). I fail to be moved though, because R.M.S. really succeeded to convince me once that _copyleft_ is indeed the only human-centered, social license, bestowing upon all future users of the software the same rights that _you_ had when you obtained it, preventing anyone to "leech" on other contributors' work. All other open-source primarily benefits for-profit corporations.

This arbitrary formal system, of course, is in fact bollocks, has little grounds in the physical universe we live in, most people pay little attention to it, and there are few disputes ever reaching court. I most certainly wouldn't ever sue and you'd most certainly do whatever you decide upon, regardless.
I personally find your kind proposal above perfectly acceptable.

**Comment by kernc** [comment]
All that said, if there's something you can contrib/extend upstream* directly (e.g. to be able to [include extra prose pages](https://github.com/pdoc3/pdoc/issues/115) was requested before), obviously very welcome.

<sub>* I would never have forked original pdoc, had they accepted my PRs. :)</sub>

**Comment by adniec** [comment]
Thank you for quick reply. I have modified license note a little bit:
>License:
This project is under the MIT License with exclusion of code interacting with [pdoc](https://pdoc3.github.io/pdoc/) which is licensed as [GNU AGPL-3.0+](https://raw.githubusercontent.com/pdoc3/pdoc/master/LICENSE.txt).
>
>Note: this extension does not modify [pdoc](https://pdoc3.github.io/pdoc/) installation. It is separate module which uses elements provided by [pdoc](https://pdoc3.github.io/pdoc/doc/pdoc/#programmatic-usage) to generate html notebook from markdown files. For this purpose original templates were downloaded and adjusted from [source](https://github.com/pdoc3/pdoc/tree/master/pdoc/templates).

Hope it will be more accurate now. Its first project created by me which in my opinion can be useful to someone. Im not so fluent in terms of licensing. I am just a student, but keep learning. I would like to leave my code totally open for anyone and don't violate your license agreements.  Hopefully with note above it will be allright. Thank you for invitation to contributing, but I think that I will need to get more practise before joining such a big project. I am going to focus on this smaller script at the moment.

**Comment by kernc** [comment]
Sounds alright to me. You are welcome, thanks, and good luck!
